# fly.toml app configuration file generated for rslangbe on 2023-05-21T17:05:58+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rslangbe"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  PORT = 3000
  HOST = 0.0.0.0